### ISSUE TITLE
ERROR - service myserv mllib bad param: no deploy file in ../../models/ggnet for initializing the net

### ISSUE THREAD

**Issue by voidabhi** [beniz/deepdetect#105]
I am getting this error while running following command:

```bash
curl -X POST "http://localhost:8080/predict" -d "{\"service\":\"myserv\",\"parameters\":{\"input\":{\"width\":125,\"height\":93},\"output\":{\"best\":3}},\"data\":[\"path/to/image\"]}"
```

On doing `ls` `../../models/ggnet` gives

```
deploy.prototxt  googlenet.prototxt  googlenet_solver.prototxt	model.json
```

i.e `deploy.prototxt` exists in the path.

Kindly guide me through this. What am i doing wrong?

**Comment by beniz** [comment]
Hi, can you share the `PUT services` call as well as the output from the server ? The server is probably not reading from the repository you are listing files from.

As a tip, try to not use relative paths for models and data repositories as they can only be relative to the directory the server has been started from.

**Comment by voidabhi** [comment]
Thanks for reverting :)

Here is the python script through which i had created the service

```python
from dd_client import DD
dd = DD('localhost')
dd.set_return_format(dd.RETURN_PYTHON)
description = 'image classification service'
mllib = 'caffe'
model = {'templates':'../templates/caffe/','repository':'../../models/ggnet'}
parameters_input = {'connector':'image'}
parameters_mllib = {'template':'googlenet','nclasses':1000}
parameters_output = {}
print dd.put_service('imageserv',model,description,mllib,
               parameters_input,parameters_mllib,parameters_output)
```

**Comment by beniz** [comment]
Try passing an absolute path to `repository`, that is the most likely error here.

**Comment by voidabhi** [comment]
Tried it with `/opt/models/ggnet`. Getting the same error.

Also, I am running dd server inside docker (ubuntu) and this script outside. Is that right?

**Comment by beniz** [comment]
Your docker container cannot read outside of its own filesystem without some work. By default, our docker container mounts `/data` for internal use. You can either move your model inside the container, or create /data and put it in there to then try to get the server to access it from within the container. In all cases I suggest you read a bit on how to share filesystem between outside and inside docker containers, especially if the two options above do not work easily for you.

**Comment by voidabhi** [comment]
I guess i have communicated wrong.

The complete dd project including `templates` and `models` are inside the docker container filesystem.
Only the `script` for creating and testing services are outside.

**Comment by beniz** [comment]
Please come onto https://gitter.im/beniz/deepdetect as this would take too long within a ticket.

**Comment by beniz** [comment]
[closed by mistake]

**Comment by beniz** [comment]
@voidabhi have you succeeded (or given up) ?

**Comment by voidabhi** [comment]
@beniz Unfortunately when i had tried again with my updates in dockerfile it didn't work. Didn't get time in between to resolve the issue.

**Comment by beniz** [comment]
@voidabhi my apologies for the delay. So, I've taken time to give it a try and your Python script needs to be modified to not use the `template` parameter, as below:
```Python
from dd_client import DD
dd = DD('localhost')
dd.set_return_format(dd.RETURN_PYTHON)
description = 'image classification service'
mllib = 'caffe'
model = {'repository':'../../models/ggnet'}
parameters_input = {'connector':'image'}
parameters_mllib = {'nclasses':1000}
parameters_output = {}
print dd.put_service('myserv',model,description,mllib,
               parameters_input,parameters_mllib,parameters_output)
```

That is, use the `template` parameter to create the neural net architecture once, and after that remove it.

The reason is that there's a pre-trained model in `/opt/models/ggnet` after the service has been created once. The deepdetect server now includes a protection against using a `template` when a model and its neural net architecture files are already in a repository (https://github.com/beniz/deepdetect/commit/d84ea7f5f92aead307f860a7ce2bc28fc7ace334). While this is generating issues to new users, it was a mandatory step to ensure that production systems cannot be broken (and net architecture lost) with a missplaced API call.

In the case of the docker deepdetect container documentation, I still consider this is a bug. The solution we are slowly converging to is to add an `override` on/off toggle to the API.

**Comment by beniz** [comment]
The commit above fixes the issue, and README has been updated. Closing. cc @voidabhi in case you decide to retry, let us know how it goes.

**Comment by xiaoqx** [comment]
It seems the files type in docker are read as  DT_UNKNOWN, so add the "DT_UNKNOWN" files to the file list could solver the problem in my case.
