### ISSUE TITLE
Add configurable parameter for INCLUDE in the modified verision of caffe

### ISSUE THREAD

**Issue by mikeatm** [beniz/deepdetect#134]
in this file thats downloaded at compile time : https://github.com/beniz/caffe/archive/master_dd_integ.tar.gz
the Makefile.config hardcodes all the include  directories,  and for  distros that install includes in non standard places, there is no way to add an alternative CFLAGS /INCLUDE dir, like fedora, which places openblas in /usr/include/openblas, 
Help.

**Comment by beniz** [comment]
Hi @mikeatm unfortunately this is a Caffe issue at the moment. Caffe can be built using `cmake` but it wasn't fully ready last time we checked.

Only Ubuntu 14.04 LTS is supported on our side unfortunately at the moment, mostly due to CUDA and other inconveniences of this kind.

If you really need to build on Fedora, the support we can offer at the moment would require that you build https://github.com/beniz/caffe/ on your own, outside of deepdetect, then we can show you how to build deepdetect using that pre-built Caffe. Let me know if you'd like to pursue that path, and note that you may encounter more difficulties on the way.

FYI, and just in case it'd be useful for you, there are docker containers available for both CPU and GPU versions.

**Comment by mikeatm** [comment]
It would be  nice to see your instructions on  building  /beniz/caffe on my own. Thanks for the docker suggestion, but im doing this work  in a low memory virtualized environment, docker might not be the best fit  for  trying deepdetect out, but i stand to be corrected on that.

**Comment by beniz** [comment]
For building Caffe, you'd need to modify the files as needed for your platform. What I meant is that once Caffe is built, you should be able to build dd and link to your own build of Caffe easily. But bear in mind, we're not supporting other platforms than Ubuntu 14.04 LTS (though 15.10 and 16.04 LTS work fine) because it is difficult and time consuming to do so.

Also, dd with Caffe in low memory settings may be looking for some trouble, or at least some reduced capabilities regarding the size of neural nets.

Why not trying the docker container and see what it does for you first ?

**Comment by mikeatm** [comment]
ok,  that sounds reasonable, il take a look at docker.

**Comment by beniz** [comment]
Thanks, it is within roadmap to eventually use the `cmake` build of Caffe at some point.
