### ISSUE TITLE
Mean subtraction at inference time

### ISSUE THREAD

**Issue by qqpwx33** [beniz/deepdetect#200]
I was wondering how mean subtraction is working in deepdetect at inference time. Looking at the image classification example http://www.deepdetect.com/tutorials/imagenet-classifier/ using googlenet I am not seeing that the mean.binaryproto / mean.npy seems to be used for inference although during training the per pixel / channel mean has been subtracted for e.g. googlenet (or other nets). Or is this somehow automatically done behind the scenes (and if so how exactly)? Many thanks!
(If I am understanding source code correct during training an available file called mean.binaryproto will be used if such named file is available)

**Comment by beniz** [comment]
Mean substraction for image classification with Caffe backend works as follows:

- Inference: if `mean.binaryproto` is available it is loaded once, and all `predict` calls subtract the values from every input image; If not available, it is ignored.

- Training: DD automatically generates and uses `mean.binaryproto` based on the training set of images.

Experience with image convnets is that in the end the mean subtraction doesn't affect the results much. As suh it is not part of the tutorial in order to keep things simple, but you are correct that it'd be a good practice to add it.

Another now current practice appears to be to scale all RGB pixel values in between -1 and 1. This is a typical practice used in Google's released models with Tensorflow. I've noticed this when integrating them recently (#30). All in all I am not sure nor convinced there's a significant impact on results, but such an assertion might be buried in one of the many papers released this year. Let me know if you have results to share about this.

**Comment by qqpwx33** [comment]
@beniz ok many thx! Two more question related to pre-processing at inference time: 

1. setting 'width' and 'height' in prediction from service (http://www.deepdetect.com/api/#prediction-from-service) lead to the same effect as net.blobs['data'].reshape(batch_size,3,width,height) using caffe.io.Transformer e.g. in step 3 in https://github.com/BVLC/caffe/blob/master/examples/00-classification.ipynb

2. If I want to oversample an image like in caffe.io.oversample(...) (https://github.com/BVLC/caffe/blob/master/python/caffe/classifier.py) I would need to adjust source code or would need to do that manually before deepdetect?

**Comment by beniz** [comment]
Hi, can you ask these in the gitter chatroom ? Issues are for bugs and improvements. thanks!

**Comment by beniz** [comment]
Regarding averaging of corners and mirrors you can either modify the source code and PR the diff, or work outside the server via the Python client.
