### ISSUE TITLE
Deepdetect crashed after 3 days of intensive prediction requests

### ISSUE THREAD

**Issue by rguilmont** [beniz/deepdetect#207]
I was benchmarking Deepdetect when suddenly, it crashed. Here is the log : 

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  remote_endpoint: Transport endpoint is not connected

```

**Comment by beniz** [comment]
Thanks, appears to potentially be a `cppnetlib` known bug, https://github.com/cpp-netlib/cpp-netlib/issues/677

Could try to build DD against and up to date version of `cppnetlib`, as follows:

**Only on Ubuntu 16.04 due to Boost 1.58 dependency**

```
sudo aptitude remove libcppnetlib-dev libcppnetlib0
git clone https://github.com/cpp-netlib/cpp-netlib.git
cd cpp-netlib
git submodule init
git submodule update
mkdir build
cd build
cmake ..
cmake ..
make
sudo make install
```
Then compile DD according to https://github.com/beniz/deepdetect/issues/126

Let me know of any issue.

**Comment by beniz** [comment]
Any update on this ? Thanks.

**Comment by rguilmont** [comment]
After some intensive predictions during more than 1 week, i can tell that with Ubuntu 16.04 ( without compiling `cppnetlit`, it doesn't crash anymore :)

**Comment by beniz** [comment]
Great, thanks.
