### ISSUE TITLE
gamma & stepsize need to be specified to Caffe backend

### ISSUE THREAD

**Issue by EBazarov** [beniz/deepdetect#360]
#### Configuration
- DeepDetect [ commit `ab7bae2b9a0b994efeb95be4aa836385beccd6f8` ]
- Ubuntu 16.04 LTS

#### Problem :
The `None`, `Null`, `N/A` values in request to DeepDetect could affect it's training. I think that it's good practice to use default value or accept `None` when it's provided.
In example below DeepDetect are **core dumping** when `stepsize` set to `null`.

#### Error message (if any) / steps to reproduce the problem:
- Train API call params **(JSON format)**:
```
	{
		"async": true,
		"data": [
			"path/to/train.svm",
			"path/to/test.svm"
		],
		"parameters":{
			"input": {
				"db": true
			},
			"mllib": {
				"gpu": true,
				"gpuid": 0,
				"resume": false,
				"class_weights": [1.0, 1.0],
				"ignore_label": null,
				"solver": {
					"iterations": 1000,
					"snapshot": null,
					"snapshot_prefix": null,
					"solver_type": "ADAM",
					"test_interval": 200,
					"test_initialization": false,
					"lr_policy": "step",
					"base_lr": 0.001,
					"gamma": null,
					"stepsize": null,
					"momentum": null,
					"weight_decay": null,
					"power": null,
					"iter_size": 1
				},
				"net": {
					"batch_size": 128,
					"test_batch_size": 16
				}
			},
			"output": {
				"best": 2,
				"measure": ["accp", "mcll", "f1"]
			}
		}
	}
```
- Server log output:
```
INFO - 10:45:36 - Network initialization done.
INFO - 10:45:36 - Solver scaffolding done.
I1128 10:45:36.396128 26226 caffelib.cc:812] smoothed_loss=0.696376
[1]    25831 floating point exception (core dumped)  ./dede
```

**Comment by beniz** [comment]
Hello, that's a good question. At the moment, the rational behind the server is that an unused parameter should be unset (i.e. not appear). The fact that the server can be killed remotely by giving `null` values qualifies as a bug, and ignoring the null values would be a solution. Thanks for catching this!

**Comment by beniz** [comment]
From looking at DD internals, `null` values are already ignored (i.e. removed). I believe the issue comes from specifying `"lr_policy": "step"` while setting `stepsize` and `gamma` to `null`. Could you retry your initial example with a non-null `stepsize` and `gamma` and report whether the crash still occurs ? Thanks.

**Comment by EBazarov** [comment]
Yes we had investigated in this issue with @YaYaB , looks like a caffe had some difficulties of raising an error if some parameters are not correctly set. I will try what you suggested and will come back to you

**Comment by YaYaB** [comment]
Indeed @beniz, I created a pull request in Caffe's repository.
https://github.com/BVLC/caffe/pull/6104

Basically in DD you catch the log FATAL of Caffe and raise an error instead of core dump. I found that they do not raise a log FATAL in case of updating the learning rate in `sgd_solver.cpp` so I added it in the code using the `CHECK` method.

I tested it using DeepDetect build on a Caffe with my modifications and it works well. An error is sent to the user, no more core dump.

**Comment by EBazarov** [comment]
Checked with setted params `stepsize` and `gamma`, works fine without core dump

**Comment by YaYaB** [comment]
Yep, basically it comes from this very specific line:
https://github.com/BVLC/caffe/blob/536851c00e44d545649648b372503f52a89c0499/src/caffe/solvers/sgd_solver.cpp#L33
Here they divide by `stepsize` that when not specified seem to be initialized to 0, thus create core dump

**Comment by beniz** [comment]
This has been merged into our custom Caffe, https://github.com/beniz/caffe/commit/ee7247f5c64d732b7b3e4cad1146dc025f700997
Thanks @YaYaB
