### ISSUE TITLE
crash when `remain_time` is not available

### ISSUE THREAD

**Issue by EBazarov** [beniz/deepdetect#383]
Last version of DeepDetect with ETA features stopped working in my pipeline. There's an issue when I try to create LMDB file and in the same time make call to get stats for training. @YaYaB has more information about that and quick fix ;)

Cheers

**Comment by beniz** [comment]
One of the `measures` in output is not a float anymore, and you may have to adapt to this (we did on our side).

**Comment by YaYaB** [comment]
@beniz Thanks for the latest feature with Estimated Time, it's really nice. However when I try to run a training it fails and returns the following error:
`{"code":500,"msg":"InternalError","dd_code":1007,"dd_msg":"in get()"}`

It's due to the fact that DD tries to compute estimated remain time each time it collects measures (https://github.com/beniz/deepdetect/blob/2306677f720ead4872ae7e5b158021b1536c0553/src/mlservice.h line 257). It needs the measure  `remain_time` however it's not always computed. At the very beginning of the training it does not appear.

**Comment by beniz** [comment]
Ah good catch, will look at it.

**Comment by YaYaB** [comment]
Chek PR https://github.com/beniz/deepdetect/pull/384
