### ISSUE TITLE
Authentication / login

### ISSUE THREAD

**Issue by revilokeb** [beniz/deepdetect#49]
@beniz is there currently a way to use authentication in deepdetect, for example something like basic http authentication, i.e. special http header with username:password via https, or anything else? (btw: many thanks for this fantastic tool!)

**Comment by beniz** [comment]
I believe building the security into dd would be a sort of design error as so many strong tools do handle it carefully out there. What you appear to be looking for should be easily achieved by using `nginx`, `apache` or other secured web server in proxy mode serving, for instance, the outside world, while dd is kept listening on localhost. This would be a safe and secure approach.

FTR, the `cppnetlib` that underlies dd's HTTP server [has support for `https`](https://github.com/cpp-netlib/cpp-netlib/tree/master/libs/network/example/http/ssl), so if a PR comes up, it would be considered.

**Comment by beniz** [comment]
BTW, since you've been around for some time, we are interested in gathering thoughts and feedback on what the most common use cases are for dd outside of our current set of applications, as well as missing features, good things to have, design flaws, etc... This type of information is welcome if you can take the time to share.

**Comment by revilokeb** [comment]
Ok I see, makes sense, thanks for elaborating.

We are still evaluating deepdetect for certain image regognition tasks, but I will share some of our use cases etc in more detail in case deepdetect will be used in production mode / for real business tasks. As mentioned so far we are pretty happy and we are seeing quite some potential for usefully applying it for our purposes. At the moment of particular importance to us is e.g. py-faster-rcnn (as mentioned in #43) and improving on the standard model architectures for imagenet classification based on recent publications, so inception-3, residual net etc

**Comment by beniz** [comment]
Thanks for sharing. Resnet templates for Imagenet-like datasets are already on the way, though it is fair to note that templating is a bit awkward since the construction of these nets is much more adhoc than that of highway networks for instance.

Regarding Faster-CNN and #43, py-faster-rcnn is not exactly there in terms of being a commodity. I'll put some technical details of why it is so directly into #43. The consequence is that it is not a straightforward task and thus at the moment the decision is still that some form of support is needed.

**Comment by beniz** [comment]
@revilokeb FYI first ResNet availability is available through #60

**Comment by revilokeb** [comment]
Great, thanks for letting me know! I will definitely have a look and test. 

The other recently improved architecture with similar performance, inception v3 from http://arxiv.org/abs/1512.00567, is available on tensorflow and mxnet (https://github.com/dmlc/mxnet-model-gallery/) but to my knowledge has not been ported to caffe so far.

**Comment by beniz** [comment]
> The other recently improved architecture with similar performance, inception v3

Maybe contributing a Caffe shema `prototxt` file for it could be a good first step ?

**Comment by revilokeb** [comment]
That would be a natural first step indeed, and happy to do so when I am having it myself. Comment was more to see if somebody out there has it already available and I have overlooked it. For the time being it  has been quicker for me to switch between frameworks to use that architecture than to convert schemas / trained models, but will for sure provide it if I am going to make it work in Caffe.
